# Generated by Django 4.2.17 on 2025-06-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0002_publication_affiliations_publication_authors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="affiliations",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="authors",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="bibtex",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="publication_links",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="sections",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="team",
        ),
    ]
