# Generated by Django 4.2.17 on 2025-06-24 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0003_remove_publication_affiliations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="affiliations",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="authors",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="bibtex",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="cover_image",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="publication_links",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="sections",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="team",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
