# Generated by Django 4.2.17 on 2025-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("areas", "0004_news_affiliations_news_authors_news_bibtex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="page_url",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
